/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author FP
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIzquierda = new javax.swing.JPanel();
        jPanelDerecha = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jTFContraseña = new javax.swing.JPasswordField();
        jBCrearUsuario = new javax.swing.JButton();
        jBAccesoUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelIzquierda.setBackground(new java.awt.Color(255, 204, 0));

        jPanelDerecha.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDerecha.setForeground(new java.awt.Color(255, 255, 255));

        jLUsuario.setBackground(new java.awt.Color(255, 204, 0));
        jLUsuario.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLUsuario.setText("Usuario:");
        jLUsuario.setOpaque(true);

        jLContraseña.setBackground(new java.awt.Color(255, 204, 0));
        jLContraseña.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLContraseña.setText("Contraseña:");
        jLContraseña.setOpaque(true);

        jTFUsuario.setBackground(new java.awt.Color(255, 255, 51));
        jTFUsuario.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTFUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });

        jTFContraseña.setBackground(new java.awt.Color(255, 255, 51));
        jTFContraseña.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTFContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jTFContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFContraseñaActionPerformed(evt);
            }
        });

        jBCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jBCrearUsuario.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jBCrearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jBCrearUsuario.setText("Crear Usuario");
        jBCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearUsuarioActionPerformed(evt);
            }
        });

        jBAccesoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jBAccesoUsuario.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jBAccesoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jBAccesoUsuario.setText("Acceso Usuario");
        jBAccesoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAccesoUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Has olvidado tu contraseña?");

        javax.swing.GroupLayout jPanelDerechaLayout = new javax.swing.GroupLayout(jPanelDerecha);
        jPanelDerecha.setLayout(jPanelDerechaLayout);
        jPanelDerechaLayout.setHorizontalGroup(
            jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDerechaLayout.createSequentialGroup()
                .addGroup(jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDerechaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTFContraseña)))
                    .addGroup(jPanelDerechaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jBCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBAccesoUsuario))
                    .addGroup(jPanelDerechaLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDerechaLayout.setVerticalGroup(
            jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDerechaLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDerechaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDerechaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFContraseña)))
                .addGap(35, 35, 35)
                .addGroup(jPanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearUsuario)
                    .addComponent(jBAccesoUsuario))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout jPanelIzquierdaLayout = new javax.swing.GroupLayout(jPanelIzquierda);
        jPanelIzquierda.setLayout(jPanelIzquierdaLayout);
        jPanelIzquierdaLayout.setHorizontalGroup(
            jPanelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIzquierdaLayout.createSequentialGroup()
                .addGap(0, 131, Short.MAX_VALUE)
                .addComponent(jPanelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelIzquierdaLayout.setVerticalGroup(
            jPanelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDerecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        jTFUsuario.setForeground(Color.red);
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jBAccesoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAccesoUsuarioActionPerformed
        usuario = jTFUsuario.getText();
        contraseña = jTFContraseña.getPassword().toString();
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "fp.2023"); Statement sentencia = con.createStatement();) {
            if (existeUsuario(usuario, contraseña, con)) {
                System.out.println("Has accedido");
            } else {
                System.out.println("El usuario no existe");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBAccesoUsuarioActionPerformed

    private void jTFContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFContraseñaActionPerformed
        
    }//GEN-LAST:event_jTFContraseñaActionPerformed

    private void jBCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearUsuarioActionPerformed
        usuario = jTFUsuario.getText();
        contraseña = jTFContraseña.getPassword().toString();
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "fp.2023"); Statement sentencia = con.createStatement();) {
            if (!existeUsuario(usuario, contraseña, con)) {
                altaUsuario(usuario, contraseña, con);
                System.out.println("Usuario creado");
            } else {
                System.out.println("El usuario ya existe");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    private static boolean existeUsuario(String usuario, String contraseña, Connection con) throws SQLException {
        String sentenciaUsuario1 = "SELECT * FROM Usuarios WHERE nombre = '" + usuario + "'";
        String sentenciaUsuario2 = "SELECT * FROM Usuarios WHERE contraseña = '" + contraseña + "'";
        ResultSet sentenciaSelect1 = con.createStatement().executeQuery(sentenciaUsuario1);
        ResultSet sentenciaSelect2 = con.createStatement().executeQuery(sentenciaUsuario2);
        if (!sentenciaSelect1.next()) {
            if (!sentenciaSelect2.next()) {
                return false;
            } else {
                return true;
            }
        } else {
            return true;
        }
    }
    
    private static void altaUsuario(String usuario, String contraseña, Connection con) throws SQLException {
        String sentenciaUsuario = "INSERT INTO Usuarios VALUES ('" + usuario + "','" + contraseña + "')";
        con.createStatement().executeUpdate(sentenciaUsuario);
    }
    
    public static void main(String args[]) {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "fp.2023");) {
            System.out.println("Conexion correcta");
        } catch (SQLException e) {
            System.out.println("Conexcion incorrecta");
            System.out.println(e.getMessage());
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    String usuario;
    String contraseña;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAccesoUsuario;
    private javax.swing.JButton jBCrearUsuario;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDerecha;
    private javax.swing.JPanel jPanelIzquierda;
    private javax.swing.JPasswordField jTFContraseña;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
